application:
  repository:
    query-limit-warning-ms: 300

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: dev
